// Archivo generado por actualizar_datos.py. No editar a mano.
window.FI_DATA = {
  "DATA": {
    "OCPF": {
      "name": "OCP — Fresco",
      "short": "OCP Fresco",
      "type": "fresco",
      "desc": "Paquete de óvulos por categoría",
      "link": "https://canva.link/47wamjk3t3bi2qj",
      "cats": [
        {
          "c": "Categoría 1",
          "p": 355000.0
        },
        {
          "c": "Categoría 2",
          "p": 278000.0
        },
        {
          "c": "Categoría 3",
          "p": 170000.0
        },
        {
          "c": "Categoría 4",
          "p": 77500.0
        }
      ]
    },
    "OCPC": {
      "name": "OCP — Congelado",
      "short": "OCP Congelado",
      "type": "congelado",
      "desc": "Precio por unidad",
      "link": "https://canva.link/0n1fzl2r4fn2kkz",
      "cats": [
        {
          "c": "Categoría 1",
          "cost": null,
          "p": 51700.0
        },
        {
          "c": "Categoría 2",
          "cost": null,
          "p": 40400.0
        },
        {
          "c": "Categoría 3",
          "cost": null,
          "p": 24800.0
        },
        {
          "c": "Categoría 4",
          "cost": null,
          "p": 12400.0
        }
      ]
    },
    "OVO": {
      "name": "Ovodonors",
      "short": "Ovodonors",
      "type": "congelado",
      "desc": "Por donante: lote o por óvulo",
      "link": "https://canva.link/4hsyllf6psxx0cw",
      "donors": [
        {
          "code": 100,
          "eggs": 10,
          "cost": null,
          "pack": 435000.0,
          "unit": 44000.0,
          "av": "3 packs de 5, 1 pack de 8"
        },
        {
          "code": 198,
          "eggs": 10,
          "cost": null,
          "pack": 335000.0,
          "unit": 34000.0,
          "av": "2 packs de 10, 1 pack de 4"
        },
        {
          "code": 242,
          "eggs": 10,
          "cost": null,
          "pack": 345000.0,
          "unit": 35000.0,
          "av": ""
        },
        {
          "code": 310,
          "eggs": 6,
          "cost": null,
          "pack": 259000.0,
          "unit": 44000.0,
          "av": ""
        },
        {
          "code": 390,
          "eggs": 8,
          "cost": null,
          "pack": 275000.0,
          "unit": 35000.0,
          "av": ""
        },
        {
          "code": 543,
          "eggs": 8,
          "cost": null,
          "pack": 315000.0,
          "unit": 40000.0,
          "av": ""
        },
        {
          "code": 447,
          "eggs": 8,
          "cost": null,
          "pack": 275000.0,
          "unit": 35000.0,
          "av": ""
        },
        {
          "code": 648,
          "eggs": 8,
          "cost": null,
          "pack": 299000.0,
          "unit": 38000.0,
          "av": "3 packs de 4, 1 pack de 5"
        },
        {
          "code": 286,
          "eggs": 12,
          "cost": null,
          "pack": 313000.0,
          "unit": 26500.0,
          "av": "8 packs de 6, 1 pack de 4, 1 pack de 3"
        },
        {
          "code": 681,
          "eggs": 6,
          "cost": null,
          "pack": 223000.0,
          "unit": 38000.0,
          "av": ""
        },
        {
          "code": 244,
          "eggs": 9,
          "cost": null,
          "pack": 670000.0,
          "unit": 75000.0,
          "av": ""
        },
        {
          "code": 669,
          "eggs": 15,
          "cost": null,
          "pack": 400000.0,
          "unit": 27000.0,
          "av": ""
        },
        {
          "code": 664,
          "eggs": 8,
          "cost": null,
          "pack": 315000.0,
          "unit": 40000.0,
          "av": ""
        },
        {
          "code": 508,
          "eggs": 14,
          "cost": null,
          "pack": 331000.0,
          "unit": 24000.0,
          "av": "2 packs de 7"
        },
        {
          "code": 739,
          "eggs": 15,
          "cost": null,
          "pack": 325000.0,
          "unit": 22000.0,
          "av": "3 packs de 15"
        },
        {
          "code": 424,
          "eggs": 12,
          "cost": null,
          "pack": 307000.0,
          "unit": 26000.0,
          "av": "7 packs de 6, 1 pack de 2"
        },
        {
          "code": 1001,
          "eggs": 10,
          "cost": null,
          "pack": 265000.0,
          "unit": 27000.0,
          "av": "Disponibles: 34 óvulos"
        },
        {
          "code": 1002,
          "eggs": 10,
          "cost": null,
          "pack": 265000.0,
          "unit": 27000.0,
          "av": "Disponibles: 11 óvulos"
        },
        {
          "code": 1003,
          "eggs": 10,
          "cost": null,
          "pack": 265000.0,
          "unit": 27000.0,
          "av": "Disponibles: 10 óvulos"
        }
      ]
    }
  },
  "SPERM": {
    "LAFER": {
      "name": "LAFER",
      "link": "https://canva.link/prhkcb3w7ieja2z",
      "origins": [
        {
          "o": "Nacional",
          "p": 18000.0,
          "ship": 15000.0,
          "t": "Traslado nacional aplica"
        },
        {
          "o": "Extranjero",
          "p": 23000.0,
          "ship": 15000.0,
          "t": ""
        },
        {
          "o": "Europeo",
          "p": 28000.0,
          "ship": 0,
          "t": "Traslado local sin costo"
        }
      ]
    },
    "GENEVITY": {
      "name": "Genevity",
      "link": "https://canva.link/0n1fzl2r4fn2kkz",
      "origins": [
        {
          "o": "Desde Europa",
          "p": 78000.0,
          "ship": 0,
          "t": "Entrega 2 – 4 semanas · Proveedor internacional"
        },
        {
          "o": "Internacional Desde Monterrey",
          "p": 62000.0,
          "ship": 0,
          "t": "Entrega 48 horas · Stock local"
        },
        {
          "o": "Desde Monterrey nacional",
          "p": 28000.0,
          "ship": 0,
          "t": "Entrega 48 horas · Stock local"
        }
      ]
    }
  },
  "SEMEN_OVO": {
    "envio": 0.0,
    "margen": 0.35,
    "iva": 0.16,
    "donors": [
      {
        "id": "0002",
        "edad": 39.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 89.0,
        "altura": 188.0,
        "sangre": "O+",
        "estudio": "Contabilidad",
        "ocupacion": "Comerciante",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0003",
        "edad": 35.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Española/Italiana/Rusa",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Rubio",
        "tipoCabello": "Ondulado",
        "peso": 78.0,
        "altura": 184.0,
        "sangre": "A-",
        "estudio": "Cultura Fìsica",
        "ocupacion": "Coach Fìsico",
        "tatuajes": "Sí",
        "documento": "Otro documento",
        "pais": "Argentina",
        "categoria": "Élite",
        "estatus": "Disponible",
        "precio": 98154,
        "cost": null
      },
      {
        "id": "0004",
        "edad": 35.0,
        "etnia": "Rusia",
        "etniaDet": "Rusa",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 77.0,
        "altura": 187.0,
        "sangre": "O+",
        "estudio": "Cultura Fìsica",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "No",
        "documento": "Otro documento",
        "pais": "Rusia",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 64246,
        "cost": null
      },
      {
        "id": "0005",
        "edad": 31.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Rizado",
        "peso": 70.0,
        "altura": 178.0,
        "sangre": "O-",
        "estudio": "Cultura Física",
        "ocupacion": "Ventas",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0006",
        "edad": 37.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 186.0,
        "sangre": "O+",
        "estudio": "Quìmica",
        "ocupacion": "Modelo",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Mèxico",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0007",
        "edad": 28.0,
        "etnia": "Cuba",
        "etniaDet": "Cubana",
        "complexion": "Delgada",
        "piel": "Negra",
        "ojos": "Café",
        "cabello": "Negro",
        "tipoCabello": "Afro",
        "peso": 85.0,
        "altura": 185.0,
        "sangre": "A+",
        "estudio": "Deportes",
        "ocupacion": "Modelo",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Cuba",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0008",
        "edad": 34.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño",
        "tipoCabello": "Ondulado",
        "peso": 78.0,
        "altura": 185.0,
        "sangre": "A+",
        "estudio": "Biología",
        "ocupacion": "Modelo y Biólogo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Mèxico",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0009",
        "edad": 39.0,
        "etnia": "Brasil",
        "etniaDet": "Brasileña",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Castaño",
        "tipoCabello": "Rizado",
        "peso": 86.0,
        "altura": 188.0,
        "sangre": "A+",
        "estudio": "Derecho",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Brasil",
        "categoria": "Premium",
        "estatus": "Vendido",
        "precio": 89231,
        "cost": null
      },
      {
        "id": "0010",
        "edad": 37.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 185.0,
        "sangre": "A-",
        "estudio": "Metafìsica",
        "ocupacion": "Modelo, Actor y Comerciante",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Mèxico",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0011",
        "edad": 36.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Lacio",
        "peso": 85.0,
        "altura": 190.0,
        "sangre": "O+",
        "estudio": "Nutrición",
        "ocupacion": "Modelo",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Mèxico",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 64246,
        "cost": null
      },
      {
        "id": "0012",
        "edad": 36.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde/Miel",
        "cabello": "Rubio Oscuro",
        "tipoCabello": "Ondulado",
        "peso": 85.0,
        "altura": 185.0,
        "sangre": "O+",
        "estudio": "Finanzas",
        "ocupacion": "Modelo e Ingeniero",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Mèxico",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 46400,
        "cost": null
      },
      {
        "id": "0013",
        "edad": 36.0,
        "etnia": "Francia",
        "etniaDet": "Francesa",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Castaño",
        "tipoCabello": "Ondulado",
        "peso": 81.0,
        "altura": 183.0,
        "sangre": "O+",
        "estudio": "Contabilidad",
        "ocupacion": "Modelo y Maestro de Francés",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Francia",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 67815,
        "cost": null
      },
      {
        "id": "0014",
        "edad": 37.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Lacio",
        "peso": 77.0,
        "altura": 183.0,
        "sangre": "A+",
        "estudio": "Coach Físico",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 64246,
        "cost": null
      },
      {
        "id": "0015",
        "edad": 34.0,
        "etnia": "Brasil",
        "etniaDet": "Brasileña",
        "complexion": "Delgada",
        "piel": "Morena",
        "ojos": "Verde",
        "cabello": "Castaño",
        "tipoCabello": "Lacio",
        "peso": 82.0,
        "altura": 186.0,
        "sangre": "O+",
        "estudio": "Mùsico",
        "ocupacion": "Productor de Mùsica",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Brasil",
        "categoria": "Élite",
        "estatus": "Disponible",
        "precio": 178462,
        "cost": null
      },
      {
        "id": "0016",
        "edad": 26.0,
        "etnia": "México",
        "etniaDet": "Mexicana/Francesa",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Lacio",
        "peso": 70.0,
        "altura": 179.0,
        "sangre": "B+",
        "estudio": "Ciencia e Historia",
        "ocupacion": "Estudiante",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0017",
        "edad": 26.0,
        "etnia": "Venezuela",
        "etniaDet": "Venezolano/Español/Francés",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Castaño",
        "tipoCabello": "Lacio",
        "peso": 78.0,
        "altura": 183.0,
        "sangre": "O+",
        "estudio": "Ciencias Sociales",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "No",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0018",
        "edad": 33.0,
        "etnia": "Argentina",
        "etniaDet": "Argentino/Alemàn/Rumano",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Azul",
        "cabello": "Castaño",
        "tipoCabello": "Lacio",
        "peso": 87.0,
        "altura": 190.0,
        "sangre": "O+",
        "estudio": "Bienes Raìces",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Cdmx",
        "categoria": "Élite",
        "estatus": "Disponible",
        "precio": 535385,
        "cost": null
      },
      {
        "id": "0019",
        "edad": 34.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café Claro",
        "cabello": "Castaño",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 190.0,
        "sangre": "A+",
        "estudio": "Administración",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0020",
        "edad": 35.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Brasileña",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Ondulado",
        "peso": 76.0,
        "altura": 182.0,
        "sangre": "O+",
        "estudio": "Mercadotecnia Digital",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 53538,
        "cost": null
      },
      {
        "id": "0021",
        "edad": 28.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Rubio Oscuro",
        "tipoCabello": "Lacio",
        "peso": 70.0,
        "altura": 183.0,
        "sangre": "O+",
        "estudio": "Modelo",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 57108,
        "cost": null
      },
      {
        "id": "0022",
        "edad": 31.0,
        "etnia": "México",
        "etniaDet": "Mexicana/Española",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 86.0,
        "altura": 186.0,
        "sangre": "O+",
        "estudio": "Negocios",
        "ocupacion": "Negocios Internacionales",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Mexico",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0023",
        "edad": 37.0,
        "etnia": "Brasil",
        "etniaDet": "Brasileña/Italiana/Alemana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 78.0,
        "altura": 185.0,
        "sangre": "O+",
        "estudio": "Turismo y Actuación",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Brasil",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 71385,
        "cost": null
      },
      {
        "id": "0024",
        "edad": 37.0,
        "etnia": "Eslovenia",
        "etniaDet": "Eslovena/Italiana/Portuguesa",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 75.0,
        "altura": 185.0,
        "sangre": "A+",
        "estudio": "Administración y Economía",
        "ocupacion": "Modelo y Entrepreneur",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Brasil",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 80308,
        "cost": null
      },
      {
        "id": "0025",
        "edad": 36.0,
        "etnia": "Alemania",
        "etniaDet": "Alemana/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Rizado",
        "peso": 84.0,
        "altura": 188.0,
        "sangre": "O-",
        "estudio": "Computación",
        "ocupacion": "Modelo y Analista de Sistemas",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Brasil",
        "categoria": "Élite",
        "estatus": "Disponible",
        "precio": 535385,
        "cost": null
      },
      {
        "id": "0027",
        "edad": 39.0,
        "etnia": "España",
        "etniaDet": "Española",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 187.0,
        "sangre": "O+",
        "estudio": "Administración",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Venezuela",
        "categoria": "Élite",
        "estatus": "Disponible",
        "precio": 124923,
        "cost": null
      },
      {
        "id": "0028",
        "edad": 38.0,
        "etnia": "España",
        "etniaDet": "Española/Argentina/Croata",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 73.0,
        "altura": 183.0,
        "sangre": "O+",
        "estudio": "Comunicación",
        "ocupacion": "Modelo y Periodista",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 74954,
        "cost": null
      },
      {
        "id": "0029",
        "edad": 38.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 90.0,
        "altura": 190.0,
        "sangre": "A+",
        "estudio": "Psicología del Deporte",
        "ocupacion": "Modelo y Entrepreneur",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 64246,
        "cost": null
      },
      {
        "id": "0030",
        "edad": 35.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Italiana/Francesa/Española",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul/Verde",
        "cabello": "Rubio",
        "tipoCabello": "Lacio",
        "peso": 85.0,
        "altura": 185.0,
        "sangre": "No especificado",
        "estudio": "Deporte",
        "ocupacion": "Atleta, Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 67815,
        "cost": null
      },
      {
        "id": "0031",
        "edad": 32.0,
        "etnia": "Ucrania",
        "etniaDet": "Ucraniana/Alemana/Eslovaca/Noruega",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Rubio",
        "tipoCabello": "Lacio",
        "peso": 85.0,
        "altura": 188.0,
        "sangre": "O+",
        "estudio": "Escritor y Editor",
        "ocupacion": "Actor, Músico, Idiomas y Modelo",
        "tatuajes": "No",
        "documento": "Otro documento",
        "pais": "Ucrania",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 64246,
        "cost": null
      },
      {
        "id": "0032",
        "edad": 33.0,
        "etnia": "México",
        "etniaDet": "Mexicana/India",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Negro",
        "cabello": "Negro",
        "tipoCabello": "Lacio",
        "peso": 80.0,
        "altura": 187.0,
        "sangre": "O+",
        "estudio": "Mercadotecnia",
        "ocupacion": "Modelo",
        "tatuajes": "No",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0033",
        "edad": 37.0,
        "etnia": "España",
        "etniaDet": "Española/Argentina",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Negro",
        "tipoCabello": "Lacio",
        "peso": 81.0,
        "altura": 185.0,
        "sangre": "No especificado",
        "estudio": "Fitness",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Buenos Aires, Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0034",
        "edad": 33.0,
        "etnia": "Brasil",
        "etniaDet": "Brasileña",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 79.0,
        "altura": 187.0,
        "sangre": "No especificado",
        "estudio": "Modelaje",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Minas, Brasil",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0035",
        "edad": 34.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Italiana/Española",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Ondulado",
        "peso": 84.0,
        "altura": 190.0,
        "sangre": "A+",
        "estudio": "Educación Física",
        "ocupacion": "Maestro",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0036",
        "edad": 38.0,
        "etnia": "Cuba",
        "etniaDet": "Cubana/Italiana/Española",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 84.0,
        "altura": 186.0,
        "sangre": "B-",
        "estudio": "Administración",
        "ocupacion": "Gerente de Marca",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Cuba",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0037",
        "edad": 34.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Árabe/Española",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 75.0,
        "altura": 178.0,
        "sangre": "A+",
        "estudio": "Educación Física",
        "ocupacion": "Jugador de Rugby y Modelo",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0038",
        "edad": 37.0,
        "etnia": "Rusia",
        "etniaDet": "Rusa/Polaca",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Rubio",
        "tipoCabello": "Lacio",
        "peso": 72.0,
        "altura": 178.0,
        "sangre": "O+",
        "estudio": "veterinaria y Ejército Ruso",
        "ocupacion": "Veterinario, Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "Otro documento",
        "pais": "Rusia",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0039",
        "edad": 33.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Alemana",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Azul",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 78.0,
        "altura": 180.0,
        "sangre": "A+",
        "estudio": "Educación Física",
        "ocupacion": "Jugador de Fútbol y Modelo",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0042",
        "edad": 37.0,
        "etnia": "Italia",
        "etniaDet": "Italiana/Argentina",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 75.0,
        "altura": 182.0,
        "sangre": "B-",
        "estudio": "Derecho",
        "ocupacion": "Modelo, Actor y Abogado",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 80308,
        "cost": null
      },
      {
        "id": "0043",
        "edad": 32.0,
        "etnia": "México",
        "etniaDet": "Mexican",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Rubio",
        "tipoCabello": "Lacio",
        "peso": 75.0,
        "altura": 178.0,
        "sangre": "O+",
        "estudio": "Derecho",
        "ocupacion": "Modelo y Abogado",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Guadalajara",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0044",
        "edad": 33.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Catalán",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 75.0,
        "altura": 182.0,
        "sangre": "O+",
        "estudio": "Comercio",
        "ocupacion": "Bienes Raíces y Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Córdoba, Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0045",
        "edad": 34.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 74.0,
        "altura": 182.0,
        "sangre": "O+",
        "estudio": "Negocios",
        "ocupacion": "Mercadotecnia y Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Cdmx",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0046",
        "edad": 35.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Negro",
        "tipoCabello": "Ondulado",
        "peso": 74.0,
        "altura": 175.0,
        "sangre": "No especificado",
        "estudio": "Derecho",
        "ocupacion": "Negocios y Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Jalisco, México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0047",
        "edad": 34.0,
        "etnia": "Nicaragua",
        "etniaDet": "Nicaragüense/Costa Riqueña/Española",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Negro",
        "tipoCabello": "Afro",
        "peso": 83.0,
        "altura": 190.0,
        "sangre": "No especificado",
        "estudio": "Contabilidad",
        "ocupacion": "Actor y Modelo",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Costa Rica",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0048",
        "edad": 34.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Española",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 85.0,
        "altura": 188.0,
        "sangre": "A+",
        "estudio": "Periodismo",
        "ocupacion": "Periodismo Deportivo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0049",
        "edad": 32.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Rubio",
        "tipoCabello": "Ondulado",
        "peso": 75.0,
        "altura": 186.0,
        "sangre": "A+",
        "estudio": "Publicidad",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 60677,
        "cost": null
      },
      {
        "id": "0051",
        "edad": 26.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Española/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 87.0,
        "altura": 190.0,
        "sangre": "No especificado",
        "estudio": "Administraciòn de Negocios",
        "ocupacion": "Modelo y Planeador de Eventos",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 46400,
        "cost": null
      },
      {
        "id": "0053",
        "edad": 29.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Española/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul/Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 70.0,
        "altura": 182.0,
        "sangre": "B+",
        "estudio": "Actor y Modelo",
        "ocupacion": "Actor y Modelo",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0055",
        "edad": 35.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Española/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Negro",
        "cabello": "Castaño",
        "tipoCabello": "Lacio",
        "peso": 85.0,
        "altura": 186.0,
        "sangre": "A+",
        "estudio": "Modelo y Actor",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 49969,
        "cost": null
      },
      {
        "id": "0056",
        "edad": 40.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 70.0,
        "altura": 175.0,
        "sangre": "O+",
        "estudio": "Mùsica",
        "ocupacion": "Productor Musical",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0057",
        "edad": 34.0,
        "etnia": "Brasil",
        "etniaDet": "Brasileña/Italiana/Española/Alemana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Rubio",
        "tipoCabello": "Ondulado",
        "peso": 78.0,
        "altura": 191.0,
        "sangre": "No especificado",
        "estudio": "Actuación",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Brasil",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 53538,
        "cost": null
      },
      {
        "id": "0058",
        "edad": 36.0,
        "etnia": "México",
        "etniaDet": "Mexicana/Española/Portuguesa/China",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 192.0,
        "sangre": "O+",
        "estudio": "Idiomas",
        "ocupacion": "Modelo y Maestro de Idiomas",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "EUA",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0059",
        "edad": 35.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Castaño Claro",
        "tipoCabello": "Rizado",
        "peso": 70.0,
        "altura": 180.0,
        "sangre": "A+",
        "estudio": "Literatura",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 60677,
        "cost": null
      },
      {
        "id": "0060",
        "edad": 33.0,
        "etnia": "Brasil",
        "etniaDet": "Brasileña/Alemana/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 80.0,
        "altura": 180.0,
        "sangre": "O+",
        "estudio": "Ingenieria Civil",
        "ocupacion": "Ingenirero Civil",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Brasil",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0061",
        "edad": 37.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina/Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 75.0,
        "altura": 180.0,
        "sangre": "B-",
        "estudio": "Derecho",
        "ocupacion": "Abogado, Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 46400,
        "cost": null
      },
      {
        "id": "0063",
        "edad": 38.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 66.0,
        "altura": 173.0,
        "sangre": "A+",
        "estudio": "Artes Audiovisuales",
        "ocupacion": "Director Creativo",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0066",
        "edad": 33.0,
        "etnia": "México",
        "etniaDet": "Mexicana/Española/Austriaca",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 183.0,
        "sangre": "O+",
        "estudio": "Odontología",
        "ocupacion": "Dentista",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0067",
        "edad": 33.0,
        "etnia": "Brasil",
        "etniaDet": "Brasileña/Libanesa/Sueca/Alemana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Castaño",
        "tipoCabello": "Lacio",
        "peso": 78.0,
        "altura": 189.0,
        "sangre": "B+",
        "estudio": "Modelo y Actor",
        "ocupacion": "Modelo y Actor",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Brasil",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0068",
        "edad": 35.0,
        "etnia": "México",
        "etniaDet": "Mexicana/Española",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Rubio",
        "tipoCabello": "Lacio",
        "peso": 91.0,
        "altura": 185.0,
        "sangre": "O+",
        "estudio": "Artes Plásticas",
        "ocupacion": "Empresario en Restaurantes",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 46400,
        "cost": null
      },
      {
        "id": "0069",
        "edad": 29.0,
        "etnia": "Venezuela",
        "etniaDet": "Venezolana/Española",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Negro",
        "tipoCabello": "Ondulado",
        "peso": 70.0,
        "altura": 175.0,
        "sangre": "A+",
        "estudio": "Nutrición",
        "ocupacion": "Empresario",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Venezuela",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0070",
        "edad": 36.0,
        "etnia": "Francia",
        "etniaDet": "Francesa/Española",
        "complexion": "Atlética",
        "piel": "Negra",
        "ojos": "Miel",
        "cabello": "Negro",
        "tipoCabello": "Afro",
        "peso": 83.0,
        "altura": 180.0,
        "sangre": "B+",
        "estudio": "Veterinaria",
        "ocupacion": "Música y Electromecánica",
        "tatuajes": "Sí",
        "documento": "Otro documento",
        "pais": "Cuba",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0071",
        "edad": 25.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café Claro",
        "cabello": "Castaño Claro",
        "tipoCabello": "Ondulado",
        "peso": 77.0,
        "altura": 200.0,
        "sangre": "O+",
        "estudio": "Aduanal",
        "ocupacion": "Servidor Público",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Guadalajara",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0072",
        "edad": 32.0,
        "etnia": "México",
        "etniaDet": "Mexicana, Española, Francesa, Inlgesa",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 92.0,
        "altura": 189.0,
        "sangre": "O+",
        "estudio": "Actor",
        "ocupacion": "Actor",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Inglaterra",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 62462,
        "cost": null
      },
      {
        "id": "0074",
        "edad": 31.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Rubio",
        "tipoCabello": "Ondulado",
        "peso": 60.0,
        "altura": 176.0,
        "sangre": "B+",
        "estudio": "Modelo",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0075",
        "edad": 25.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Castaño",
        "tipoCabello": "Ondulado",
        "peso": 79.0,
        "altura": 182.0,
        "sangre": "O+",
        "estudio": "Modelo",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0077",
        "edad": 30.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Café Oscuro",
        "tipoCabello": "Lacio",
        "peso": 88.0,
        "altura": 184.0,
        "sangre": "A+",
        "estudio": "Nutrición",
        "ocupacion": "Nutriologo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0078",
        "edad": 29.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Negro",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 181.0,
        "sangre": "O+",
        "estudio": "Marketing y Finanzas",
        "ocupacion": "Finanzas",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0079",
        "edad": 34.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Miel",
        "cabello": "Café",
        "tipoCabello": "Lacio",
        "peso": 80.0,
        "altura": 181.0,
        "sangre": "A+",
        "estudio": "Comercio",
        "ocupacion": "Comercio",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0080",
        "edad": 38.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Miel",
        "cabello": "Café Oscuro",
        "tipoCabello": "Lacio",
        "peso": 83.0,
        "altura": 185.0,
        "sangre": "B+",
        "estudio": "Modelo",
        "ocupacion": "Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina, Brasil, Italiana",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0081",
        "edad": 36.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café Oscuro",
        "cabello": "Negro",
        "tipoCabello": "Lacio",
        "peso": 80.0,
        "altura": 178.0,
        "sangre": "O+",
        "estudio": "Administración Deportiva",
        "ocupacion": "Entrenador personal",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0082",
        "edad": 32.0,
        "etnia": "Rep. Dominicana",
        "etniaDet": "Dominicana, Cubana",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café Oscuro",
        "cabello": "Negro",
        "tipoCabello": "Ondulado",
        "peso": 72.0,
        "altura": 175.0,
        "sangre": "A+",
        "estudio": "Sociedad",
        "ocupacion": "Actor",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "República Dominicana",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0083",
        "edad": 38.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café Oscuro",
        "cabello": "Café Oscuro",
        "tipoCabello": "Lacio",
        "peso": 79.0,
        "altura": 175.0,
        "sangre": "O+",
        "estudio": "Terapia Físcia",
        "ocupacion": "Entrenador personal",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0084",
        "edad": 37.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Verde",
        "cabello": "Castaño",
        "tipoCabello": "Lacio",
        "peso": 70.0,
        "altura": 177.0,
        "sangre": "A+",
        "estudio": "Leyes",
        "ocupacion": "Abogado y Modelo",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0085",
        "edad": 32.0,
        "etnia": "Argentina Italiana",
        "etniaDet": "Argentina Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Rubio",
        "tipoCabello": "Ondulado",
        "peso": 72.0,
        "altura": 185.0,
        "sangre": "O-",
        "estudio": "Modelo",
        "ocupacion": "Modelo",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 53538,
        "cost": null
      },
      {
        "id": "0086",
        "edad": 25.0,
        "etnia": "México",
        "etniaDet": "México / Usa",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño",
        "tipoCabello": "Lacio",
        "peso": 75.0,
        "altura": 184.0,
        "sangre": "O+",
        "estudio": "Leyes",
        "ocupacion": "Leyes",
        "tatuajes": "No",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0088",
        "edad": 27.0,
        "etnia": "México",
        "etniaDet": "México",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Café",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 175.0,
        "sangre": "O+",
        "estudio": "Entrenador Modelo",
        "ocupacion": "Entrenador Modelo",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0089",
        "edad": 25.0,
        "etnia": "México",
        "etniaDet": "México",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Negro",
        "cabello": "Negro",
        "tipoCabello": "Ondulado",
        "peso": 76.0,
        "altura": 180.0,
        "sangre": "A+",
        "estudio": "Odontología",
        "ocupacion": "Odontología",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0090",
        "edad": 28.0,
        "etnia": "México",
        "etniaDet": "México",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Café",
        "tipoCabello": "Ondulado",
        "peso": 83.0,
        "altura": 190.0,
        "sangre": "O+",
        "estudio": "Negocios y Modelo",
        "ocupacion": "Negocios y modelo",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0091",
        "edad": 22.0,
        "etnia": "México",
        "etniaDet": "México",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café Claro",
        "cabello": "Café Claro",
        "tipoCabello": "Ondulado",
        "peso": 90.0,
        "altura": 183.0,
        "sangre": "O+",
        "estudio": "Leyes",
        "ocupacion": "Leyes",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0092",
        "edad": 24.0,
        "etnia": "México",
        "etniaDet": "México",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café Claro",
        "cabello": "Rubio",
        "tipoCabello": "Ondulado",
        "peso": 85.0,
        "altura": 178.0,
        "sangre": "B+",
        "estudio": "Medicina",
        "ocupacion": "Medicina",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0093",
        "edad": 28.0,
        "etnia": "México",
        "etniaDet": "México",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café Oscuro",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Ondulado",
        "peso": 82.0,
        "altura": 179.0,
        "sangre": "A+",
        "estudio": "Diplomados Eventos",
        "ocupacion": "Organizador de eventos y Florista",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0094",
        "edad": 23.0,
        "etnia": "México",
        "etniaDet": "México",
        "complexion": "Delgada",
        "piel": "Morena Clara",
        "ojos": "Café",
        "cabello": "Negro",
        "tipoCabello": "Lacio",
        "peso": 71.0,
        "altura": 183.0,
        "sangre": "O+",
        "estudio": "Aviación",
        "ocupacion": "Coach indoor cycling",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0095",
        "edad": 29.0,
        "etnia": "Argentina Italiana",
        "etniaDet": "Argentina Italiana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Rubio",
        "tipoCabello": "Lacio",
        "peso": 96.0,
        "altura": 198.0,
        "sangre": "A+",
        "estudio": "Software",
        "ocupacion": "Desarrollo Software / Modelo",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Premium",
        "estatus": "Disponible",
        "precio": 62462,
        "cost": null
      },
      {
        "id": "0096",
        "edad": 27.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café Claro",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Ondulado",
        "peso": 75.0,
        "altura": 175.0,
        "sangre": "O+",
        "estudio": "Negocios Internacionales",
        "ocupacion": "Gerente de Ventas",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0097",
        "edad": 29.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Atlética",
        "piel": "Morena Clara",
        "ojos": "Café Oscuro",
        "cabello": "Café Oscuro",
        "tipoCabello": "Ondulado",
        "peso": 90.0,
        "altura": 178.0,
        "sangre": "No especificado",
        "estudio": "Deportes",
        "ocupacion": "Entrenador de Gym",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Méxicali, BC",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0098",
        "edad": 32.0,
        "etnia": "México",
        "etniaDet": "Mexicano- Padre de mi abuelo era de Arabia",
        "complexion": "Mesomorfo",
        "piel": "Morena Clara",
        "ojos": "Negro",
        "cabello": "Negro",
        "tipoCabello": "Ondulado",
        "peso": 68.0,
        "altura": 170.0,
        "sangre": "O+",
        "estudio": "Ingeniería",
        "ocupacion": "Ingeniero de procesos",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Guadalajara, Jalisco",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0099",
        "edad": 34.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina, Italiana, Española",
        "complexion": "Atlética",
        "piel": "Blanca",
        "ojos": "Verde Claro",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 75.0,
        "altura": 180.0,
        "sangre": "O+",
        "estudio": "",
        "ocupacion": "Empresario-Comerciante",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Córdoba, Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 53538,
        "cost": null
      },
      {
        "id": "0100",
        "edad": 25.0,
        "etnia": "Italia",
        "etniaDet": "Italia/Argentina",
        "complexion": "Delgada",
        "piel": "Blanca",
        "ojos": "Café",
        "cabello": "Castaño Claro",
        "tipoCabello": "Rizado",
        "peso": 72.0,
        "altura": 174.0,
        "sangre": "A+",
        "estudio": "Naturales Informatica",
        "ocupacion": "Asistencia Administrativa",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Italia/Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0101",
        "edad": 26.0,
        "etnia": "México",
        "etniaDet": "Mexicana",
        "complexion": "Delgada",
        "piel": "Clara",
        "ojos": "Café Claro",
        "cabello": "Café Claro",
        "tipoCabello": "No especificado",
        "peso": 75.0,
        "altura": 175.0,
        "sangre": "A+",
        "estudio": "Comercio Internacional",
        "ocupacion": "",
        "tatuajes": "Sí",
        "documento": "Sí",
        "pais": "Guadalajara, Jalisco",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0102",
        "edad": 34.0,
        "etnia": "México",
        "etniaDet": "Mexicano",
        "complexion": "Mesomorfo",
        "piel": "Clara a Media",
        "ojos": "Café",
        "cabello": "Castaño",
        "tipoCabello": "Lacio",
        "peso": 84.0,
        "altura": 177.0,
        "sangre": "B+",
        "estudio": "Ciencias de la Salud",
        "ocupacion": "Médico Cirujano",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Irapuato, Gto.",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0103",
        "edad": 34.0,
        "etnia": "Argentina",
        "etniaDet": "Argentino, Italiano, Español.",
        "complexion": "Mesomorfo",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Claro",
        "tipoCabello": "Lacio",
        "peso": 79.0,
        "altura": 188.0,
        "sangre": "O+",
        "estudio": "Ciencias Humanas",
        "ocupacion": "Modelo / Personal Trainer",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Buenos Aires, Argentina..",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 53538,
        "cost": null
      },
      {
        "id": "0104",
        "edad": 31.0,
        "etnia": "Argentina",
        "etniaDet": "Argentino, Italiano, Español.",
        "complexion": "Mesomorfo",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Rubio",
        "tipoCabello": "Lacio",
        "peso": 82.0,
        "altura": 187.0,
        "sangre": "A+",
        "estudio": "Modelo Actor",
        "ocupacion": "Modelo Actor",
        "tatuajes": "No",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 53538,
        "cost": null
      },
      {
        "id": "0105",
        "edad": 24.0,
        "etnia": "México",
        "etniaDet": "Mexicana, Alemana",
        "complexion": "Mesomorfo",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Lacio",
        "peso": 80.0,
        "altura": 178.0,
        "sangre": "O+",
        "estudio": "Recursos Humanos",
        "ocupacion": "Modelo / Asesor Gastronomico",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 49969,
        "cost": null
      },
      {
        "id": "0106",
        "edad": 27.0,
        "etnia": "México",
        "etniaDet": "Mexicana, Alemana",
        "complexion": "Mesomorfo",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Castaño Oscuro",
        "tipoCabello": "Ondulado",
        "peso": 82.0,
        "altura": 175.0,
        "sangre": "O+",
        "estudio": "Arte",
        "ocupacion": "Actor",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 49969,
        "cost": null
      },
      {
        "id": "0107",
        "edad": 27.0,
        "etnia": "México",
        "etniaDet": "Mexicana, Alemana, Chilena.",
        "complexion": "Mesomorfo",
        "piel": "Blanca",
        "ojos": "Azul",
        "cabello": "Rubio",
        "tipoCabello": "Ondulado",
        "peso": 80.0,
        "altura": 185.0,
        "sangre": "O+",
        "estudio": "Turismo",
        "ocupacion": "Agente de Seguros",
        "tatuajes": "No",
        "documento": "Sí",
        "pais": "México",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      },
      {
        "id": "0108",
        "edad": 23.0,
        "etnia": "Argentina",
        "etniaDet": "Argentina.",
        "complexion": "Mesomorfo",
        "piel": "Blanca",
        "ojos": "Verde",
        "cabello": "Rubio",
        "tipoCabello": "Lacio",
        "peso": 80.0,
        "altura": 183.0,
        "sangre": "A+",
        "estudio": "Literatura",
        "ocupacion": "Empleado",
        "tatuajes": "Sí",
        "documento": "No",
        "pais": "Argentina",
        "categoria": "Estándar",
        "estatus": "Disponible",
        "precio": 44615,
        "cost": null
      }
    ]
  },
  "META": {
    "fuente": "Directorio de Bancos FI",
    "actualizaciones": "OCP 04.09.2026 · LAFER 31.08.2026 · Ovodonors 21.09.2026",
    "generado": "30.09.2026",
    "costos": false
  }
};
